//! Assert byte-for-byte agreement with the Python encoder and action schema.
//!
//! The corpus is generated by `scripts/build_conformance_corpus.py` from the
//! Python implementation. Nothing else prevents the two implementations from
//! drifting: a wrong plane produces well-formed replay shards that quietly teach
//! the network the wrong move, with no crash and no failing Python test.

use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::PathBuf;

use base64::Engine;
use serde_json::Value;
use shakmaty::uci::UciMove;
use shakmaty::{Color, Position};

use pe_search::action::{policy_index, ACTION_PLANES, POLICY_SIZE};
use pe_search::encoding::ENCODED_LEN;
use pe_search::position::GamePosition;

fn corpus_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../tests/conformance/encoding-action-corpus.jsonl")
}

struct Corpus {
    header: Value,
    records: Vec<Value>,
}

fn load() -> Corpus {
    let text = fs::read_to_string(corpus_path()).expect("conformance corpus is missing");
    let mut lines = text.lines();
    let header = serde_json::from_str(lines.next().expect("corpus header")).expect("header JSON");
    let records = lines
        .map(|line| serde_json::from_str(line).expect("record JSON"))
        .collect();
    Corpus { header, records }
}

/// Replay a record's move list, exercising the same `play` path self-play uses.
fn replay(record: &Value) -> GamePosition {
    let mut game = GamePosition::from_fen(record["initial_fen"].as_str().unwrap())
        .expect("corpus initial FEN must parse");
    for move_value in record["moves_uci"].as_array().unwrap() {
        let uci: UciMove = move_value.as_str().unwrap().parse().expect("corpus UCI");
        let legal = uci
            .to_move(game.position())
            .expect("corpus move must be legal");
        game.play(&legal);
    }
    game
}

fn record_id(record: &Value) -> &str {
    record["id"].as_str().unwrap()
}

#[test]
fn corpus_matches_the_expected_schema_versions() {
    let corpus = load();
    assert_eq!(corpus.header["encoder_version"], "v2");
    assert_eq!(corpus.header["action_schema_version"], "v1");
    assert_eq!(
        corpus.header["record_count"].as_u64().unwrap() as usize,
        corpus.records.len()
    );
}

#[test]
fn encoded_boards_match_python_byte_for_byte() {
    let corpus = load();
    let mut buffer = vec![0u8; ENCODED_LEN];
    for record in &corpus.records {
        let expected = base64::engine::general_purpose::STANDARD
            .decode(record["encoded_board_b64"].as_str().unwrap())
            .expect("base64 encoding");
        assert_eq!(expected.len(), ENCODED_LEN);
        replay(record).encode_into(&mut buffer);
        if buffer != expected {
            let first = buffer
                .iter()
                .zip(&expected)
                .position(|(a, b)| a != b)
                .unwrap();
            panic!(
                "{}: encoding differs at plane {} cell {} (rust {} vs python {})",
                record_id(record),
                first / 64,
                first % 64,
                buffer[first],
                expected[first],
            );
        }
    }
}

#[test]
fn legal_action_mapping_matches_python() {
    let corpus = load();
    for record in &corpus.records {
        let game = replay(record);
        let id = record_id(record);
        let expected: BTreeMap<String, usize> = record["legal_moves_uci"]
            .as_array()
            .unwrap()
            .iter()
            .map(|value| value.as_str().unwrap().to_string())
            .zip(
                record["legal_policy_indices"]
                    .as_array()
                    .unwrap()
                    .iter()
                    .map(|value| value.as_u64().unwrap() as usize),
            )
            .collect();

        if record["is_game_over_claim_draw"].as_bool().unwrap() {
            assert!(expected.is_empty(), "{id}");
            continue;
        }

        // Generation order is an implementation detail and legitimately differs
        // between shakmaty and python-chess. The contract is the pairing: every
        // legal move must exist in both, and must map to the same action index.
        let actual: BTreeMap<String, usize> = game
            .legal_moves()
            .iter()
            .map(|m| {
                (
                    UciMove::from_standard(m).to_string(),
                    policy_index(m, game.turn()).expect("legal move must map to an action"),
                )
            })
            .collect();

        assert_eq!(actual, expected, "{id}");
        assert!(actual.values().all(|&index| index < POLICY_SIZE), "{id}");
        assert_eq!(
            actual.values().collect::<BTreeSet<_>>().len(),
            actual.len(),
            "{id}: two legal moves collided on one action index"
        );
    }
}

#[test]
fn repetition_and_claim_rules_match_python() {
    let corpus = load();
    for record in &corpus.records {
        let game = replay(record);
        let id = record_id(record);
        assert_eq!(
            game.is_repetition(2),
            record["is_repetition_2"].as_bool().unwrap(),
            "{id}: is_repetition(2)"
        );
        assert_eq!(
            game.is_repetition(3),
            record["is_repetition_3"].as_bool().unwrap(),
            "{id}: is_repetition(3)"
        );
        assert_eq!(
            game.position().is_check(),
            record["is_check"].as_bool().unwrap(),
            "{id}: is_check"
        );
        assert_eq!(
            game.can_claim_fifty_moves(),
            record["can_claim_fifty_moves"].as_bool().unwrap(),
            "{id}: can_claim_fifty_moves"
        );
        assert_eq!(
            game.can_claim_threefold_repetition(),
            record["can_claim_threefold_repetition"].as_bool().unwrap(),
            "{id}: can_claim_threefold_repetition"
        );
    }
}

#[test]
fn terminal_status_matches_python() {
    let corpus = load();
    for record in &corpus.records {
        let game = replay(record);
        let id = record_id(record);
        let outcome = game.outcome(true);
        assert_eq!(
            outcome.is_some(),
            record["is_game_over_claim_draw"].as_bool().unwrap(),
            "{id}: is_game_over(claim_draw=True)"
        );
        let Some(outcome) = outcome else {
            assert!(record["outcome_termination"].is_null(), "{id}");
            continue;
        };
        let expected_termination = record["outcome_termination"].as_str().unwrap().to_lowercase();
        assert_eq!(outcome.termination.as_str(), expected_termination, "{id}");
        let expected_winner = record["outcome_winner"].as_str();
        let actual_winner = outcome.winner.map(|color| match color {
            Color::White => "white",
            Color::Black => "black",
        });
        assert_eq!(actual_winner, expected_winner, "{id}: winner");
    }
}

#[test]
fn corpus_reaches_every_action_plane_from_both_orientations() {
    let corpus = load();
    let mut white = BTreeSet::new();
    let mut black = BTreeSet::new();
    for record in &corpus.records {
        let target = if record["turn"] == "white" {
            &mut white
        } else {
            &mut black
        };
        for value in record["legal_policy_indices"].as_array().unwrap() {
            target.insert(value.as_u64().unwrap() as usize % ACTION_PLANES);
        }
    }
    assert_eq!(white.len(), ACTION_PLANES, "white plane coverage");
    assert_eq!(black.len(), ACTION_PLANES, "black plane coverage");
}
